### ISSUE TITLE
contributors name in the README

### ISSUE THREAD

**Issue by SharathRaparthy** [IvLabs/ResearchPaperNotes#10]
Hey! 
I am thinking it would be nice to include the author's name in the README itself.

**Comment by take2rohit** [comment]
Its a good idea.. I will create a PR and add authors name. BTW what if there are too many contributors.

**Comment by akshaykvnit** [comment]
If there are too many, then use et. al. 😂. If someone has any other solution, please do comment below.

**Comment by take2rohit** [comment]
> If there are too many, then use et. al. . If someone has any other solution, please do comment below.
> 
> But, as of now, there's only a single author for notes (generally).

Okay so other authors can add names in their respective notebooks

**Comment by take2rohit** [comment]
> > If there are too many, then use et. al. . If someone has any other solution, please do comment below.
> > But, as of now, there's only a single author for notes (generally).
> 
> Okay so other authors can add names in their respective notebooks

This seems to be the best solution:
one author name will be in readme and others in notebook

This issue can be closed now @akshaykvnit

**Comment by akshaykvnit** [comment]
@take2rohit why should it be closed? It's not fixed yet.

**Comment by SharathRaparthy** [comment]
I fixed in reinforcement-learning @akshaykvnit @take2rohit
