### ISSUE TITLE
Add badges in `README.md`

### ISSUE THREAD

**Issue by take2rohit** [IvLabs/ResearchPaperNotes#22]
please add badges for stars, license, maintained, docs passing, IvLabs logo, etc in landing page `README.md` (See resources repo)

**Comment by akshaykvnit** [comment]
What is the meaning of the docs passing badge?

**Comment by take2rohit** [comment]
![image](https://user-images.githubusercontent.com/40535193/87204615-e1092a00-c322-11ea-84c7-82980b0f796f.png)

You can see sample here in resources repo

**Comment by akshaykvnit** [comment]
@take2rohit I think you misunderstood my question. I wasn't asking what it looks like, rather what it indicates? What decides docs passing or failing?

**Comment by take2rohit** [comment]
It is of not much use and checks if documentation syntax is correct or not.  🤣 
It looks good

**Comment by akshaykvnit** [comment]
@take2rohit @aayush-fadia Just the IvLabs logo is left I think. Finish it and close this or you can skip it and close this.

**Comment by take2rohit** [comment]
Dont need ivlabs logo!
Closing this issue!
