### ISSUE TITLE
Make all tables in repo properly MD formatted

### ISSUE THREAD

**Issue by take2rohit** [IvLabs/ResearchPaperNotes#51]
http://markdowntable.com/
Use this to properly format all tables so that it looks better and becomes a readable markdown.

**Comment by jirkavrba** [comment]
I can take care of this one

**Comment by take2rohit** [comment]
ok create a pr.
but make sure u do changes on `devel` branch @jirkavrba

**Comment by jirkavrba** [comment]
Sure

**Comment by jirkavrba** [comment]
I opened a pull request at https://github.com/IvLabs/ResearchPaperNotes/pull/52

**Comment by take2rohit** [comment]
Thanks for the contributions. Closing this issue. If you liked our repo do leave a star 😄
