### ISSUE TITLE
Create a CONTRIBUTING.md

### ISSUE THREAD

**Issue by take2rohit** [IvLabs/ResearchPaperNotes#53]
- Create a proper file for contributions.

**Comment by comrade-om** [comment]
Hi @take2rohit, would be happy to start working on this issue. Can I be assigned to this?

**Comment by take2rohit** [comment]
Sure! @comrade-om 

Make sure you add 
- Add procedure on how to create PR, issue, etc. Something similar to  [THIS](https://github.com/IvLabs/resources/blob/devel/CONTRIBUTING.md)
- Also add names of maintainers in CONTRIBUTING.md
```
- [Rohit Lal](http://take2rohit.github.io/)
- [Raj Ghugare](https://www.linkedin.com/in/raj-ghugare-917137169)
- [Aditya Shirwatkar](https://in.linkedin.com/in/aditya-shirwatkar-40a956188)
- [Akshay Kulkarni](https://github.com/akshaykvnit)
```
- Add [rules of appending papers](https://github.com/IvLabs/ResearchPaperNotes/blob/master/README.md#rules-of-appending-papers)

if this is fine, I will assign you

**Comment by comrade-om** [comment]
Yes, consider it done, a humble request to add the topic hacktoberfest to the repo since they updated the [rules](https://hacktoberfest.digitalocean.com/hacktoberfest-update)

**Comment by take2rohit** [comment]
@comrade-om. Please proceed with a PR. I have assigned this to you

**Comment by comrade-om** [comment]
Yes working on it. Actually adding all the steps to create a proper pull request

**Comment by comrade-om** [comment]
@take2rohit please review my pull request :)
