### ISSUE TITLE
Create a list of subtopics in DL section for better accessibility

### ISSUE THREAD

**Issue by RajGhugare19** [IvLabs/ResearchPaperNotes#67]
The number of sub sections in DL is increasing and it would be better if we create a list of subtopics present currently, on top of the readme.
Preferably a  second year can do this to get a first hand xp about PRs and commits...

**Comment by take2rohit** [comment]
yeah you can use Collapsable markdown for subtopic. Example 

<details><summary>Deep Learning</summary>
<p>
<ul>
  <li>Domain Adaptation</li>
  <li>Object Detection</li>
  <li>Etc</li>
</ul>
</p>
</details>


Code for above is 
```HTML
<details><summary>Deep Learning</summary>
<p>
<ul>
  <li>Domain Adaptation</li>
  <li>Object Detection</li>
  <li>Etc</li>
</ul>
</p>
</details>
```
